"""RDKit fr_ function codes mapped to human-readable functional group names."""

FG_NAMES: dict[str, str] = {
    "fr_Al_COO":              "Aliphatic carboxylic acid",
    "fr_Al_OH":               "Aliphatic hydroxyl (OH)",
    "fr_Al_OH_noTert":        "Aliphatic OH (non-tertiary)",
    "fr_ArN":                 "Aromatic amine (Ar-N)",
    "fr_Ar_COO":              "Aromatic carboxylic acid",
    "fr_Ar_N":                "Aromatic nitrogen",
    "fr_Ar_NH":               "Aromatic NH",
    "fr_Ar_OH":               "Aromatic hydroxyl (phenol)",
    "fr_COO":                 "Carboxylate / ester (COO)",
    "fr_COO2":                "Carboxylic acid (COOH)",
    "fr_C_O":                 "Carbonyl (C=O)",
    "fr_C_O_noCOO":           "Carbonyl excl. COOH",
    "fr_C_S":                 "Thioester / thioether (C-S)",
    "fr_HOCCN":               "Beta-aminoalcohol",
    "fr_Imine":               "Imine (C=N)",
    "fr_NH0":                 "Tertiary amine (N, no H)",
    "fr_NH1":                 "Secondary amine (NH)",
    "fr_NH2":                 "Primary amine (NH2)",
    "fr_N_O":                 "Hydroxylamine / N-oxide",
    "fr_Ndealkylation1":      "N-dealkylation site 1",
    "fr_Ndealkylation2":      "N-dealkylation site 2",
    "fr_Nhpyrrole":           "Pyrrole-type NH",
    "fr_SH":                  "Thiol (SH)",
    "fr_aldehyde":            "Aldehyde (CHO)",
    "fr_alkyl_carbamate":     "Alkyl carbamate",
    "fr_allylic_oxid":        "Allylic oxidation site",
    "fr_amide":               "Amide (CONH)",
    "fr_amidine":             "Amidine",
    "fr_aniline":             "Aniline (Ar-NH2)",
    "fr_aryl_methyl":         "Aryl methyl",
    "fr_azide":               "Azide",
    "fr_azo":                 "Azo group (N=N)",
    "fr_barbitur":            "Barbiturate",
    "fr_benzene":             "Benzene ring",
    "fr_benzodiazepine":      "Benzodiazepine",
    "fr_bicyclic":            "Bicyclic system",
    "fr_diazo":               "Diazo group",
    "fr_dihydropyridine":     "Dihydropyridine",
    "fr_epoxide":             "Epoxide",
    "fr_ester":               "Ester",
    "fr_ether":               "Ether (C-O-C)",
    "fr_furan":               "Furan ring",
    "fr_guanido":             "Guanidine",
    "fr_halogen":             "Halogen (F/Cl/Br/I)",
    "fr_hdrzine":             "Hydrazine",
    "fr_hdrzone":             "Hydrazone",
    "fr_imidazole":           "Imidazole ring",
    "fr_imide":               "Imide",
    "fr_isocyan":             "Isocyanate",
    "fr_isothiocyan":         "Isothiocyanate",
    "fr_ketone":              "Ketone",
    "fr_ketone_Topliss":      "Ketone (Topliss)",
    "fr_lactam":              "Lactam",
    "fr_lactone":             "Lactone",
    "fr_methoxy":             "Methoxy (OCH3)",
    "fr_morpholine":          "Morpholine ring",
    "fr_nitrile":             "Nitrile (CN)",
    "fr_nitro":               "Nitro group (NO2)",
    "fr_nitro_arom":          "Aromatic nitro",
    "fr_nitro_arom_nonort":   "Aromatic nitro (non-ortho)",
    "fr_nitroso":             "Nitroso (N=O)",
    "fr_oxazole":             "Oxazole ring",
    "fr_oxime":               "Oxime (C=N-OH)",
    "fr_para_hydroxylation":  "Para-hydroxylation site",
    "fr_phenol":              "Phenol",
    "fr_phenol_noOrthoHbond": "Phenol (no ortho H-bond)",
    "fr_phos_acid":           "Phosphoric acid",
    "fr_phos_ester":          "Phosphate ester",
    "fr_piperdine":           "Piperidine ring",
    "fr_piperzine":           "Piperazine ring",
    "fr_priamide":            "Primary amide",
    "fr_prisulfonamd":        "Primary sulfonamide",
    "fr_pyridine":            "Pyridine ring",
    "fr_quatN":               "Quaternary nitrogen",
    "fr_sulfide":             "Sulfide (C-S-C)",
    "fr_sulfonamd":           "Sulfonamide",
    "fr_sulfone":             "Sulfone",
    "fr_term_acetylene":      "Terminal alkyne",
    "fr_tetrazole":           "Tetrazole ring",
    "fr_thiazole":            "Thiazole ring",
    "fr_thiocyan":            "Thiocyanate",
    "fr_thiophene":           "Thiophene ring",
    "fr_unbrch_alkane":       "Unbranched alkane",
    "fr_urea":                "Urea",
}
